[tools]
go = "latest"
"go:github.com/air-verse/air" = "latest"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest" # or install a specific version
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
node = "lts"
python = "latest"
