[tools]
bun = "latest"
go = "latest"
"go:github.com/air-verse/air" = "latest"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest" # or install a specific version
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
node = "lts"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
pnpm = "latest"
python = "latest"
uv = "latest"
"pipx:ansible" = { version = "latest", uvx_args = "--with-executables-from ansible-core,ansible-lint"}
# NOTE: The --with-executables-from flag (in `uv tool install`) will install those packages as
# dependencies (if they're not already so) AND include their executables
"pipx:ruff" = "latest"
"pipx:sqlfluff" = "latest"

[settings]

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true
