"$schema" = 'https://starship.rs/config-schema.json' # editor autocomplete

# === Prompt-wide configurations ===
palette = 'catppuccin_mocha'
command_timeout = 1000       # Default timeout for commands is 500ms
add_newline = true           # A blank line before prompt start

format = """
$character\
$username\
$sudo\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$fill\
$all
"""

# included but disabled to exclude it from $all
[character]
disabled = true
success_symbol = "[ï’](bold green)"
error_symbol = "[ï”¯](bold red)"

# === 1st Line: left hand side ===
[username]
format = "[ï• $user]($style) "

[sudo]
disabled = false
style = "bold rosewater"
# symbol = '\[sudo\] '
symbol = "î¬‘ "
format = "[$symbol]($style)"

[hostname]
ssh_only = true
ssh_symbol = "î¬º "
# ssh_symbol = "ó°£€ "
format = "[$ssh_symbol$hostname ]($style)"

[localip]
disabled = false
# only shown with SSH

[directory]
truncation_symbol = "â€¦/"
home_symbol = "ï€• ~"
truncate_to_repo = false
truncation_length = 5
style = "bold blue"

[directory.substitutions]
"~/Projects/OpenUniversity/" = "ï†œ  "
"~/Projects/" = "î¯Ÿ  "
"~/Work/" = "îª¬  "

[git_branch]
symbol = "î©¨ "
format = '[on](text dimmed) [$symbol$branch(:$remote_branch)]($style) '
style = "bold purple"

[git_commit]
format = '[on](text dimmed) [ï— $hash$tag]($style) '
style = "bold purple"
tag_disabled = false
tag_symbol = " ï€« "

[git_state]
style = "bold yellow"

[git_status]
style = "bold maroon"
format = '[$all_status$ahead_behind]($style)'
# renamed = "å‡œ "
# renamed = "è¥ "
conflicted = "ó°‡ "
up_to_date = "ï† "
# untracked = "ï”© "
untracked = "ó±„ "
# untracked = "î©¿ "
modified = "ï„ "
deleted = "ï€” "
stashed = "ó°— "
staged = '[++$count](green) '
diverged = "â‡•â‡¡($ahead_count)â‡£($behind_count) "
ahead = "â‡¡$count "
behind = "â‡£$count "

[cmd_duration]
format = "[[took](text dimmed) î™ $duration]($style)"
style = "flamingo"

# === 1st Line: right hand side ===
[nodejs]
symbol = "ó°™ "
style = "bold green"
not_capable_style = "red"
format = '[$symbol($version )]($style)'

[python]
symbol = "ó°Œ  "
style = "bold yellow"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
# it's possible to show pyenv version

[rust]
symbol = "î¨ "
style = "bold red"
format = '[$symbol($version )]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bold blue"
format = '[$symbol$context]($style) '

[vagrant]
symbol = "â± "
# symbol = "Vargrant"
style = "bold cyan"
format = '[$symbol($version )]($style)'

[java]
symbol = "î‰– "
style = "bold red"
format = '[${symbol}(${version} )]($style)'

[golang]
symbol = "ó°Ÿ“ "
style = "bold cyan"
format = '[$symbol($version )]($style)'

[package]
symbol = "ï’‡ "
format = "[$symbol$version]($style) "

[aws]
symbol = "ï’¬ "
format = "[$symbol($profile )(\\($region\\) )(\\[$duration\\] )]($style)"

[lua]
symbol = "î˜  "
format = "[$symbol($version )]($style)"

[ruby]
symbol = "îˆ "
format = "[$symbol($version )]($style)"

# === Misc. ===
[fill]
symbol = " "

# === Colour palettes ===
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# [os.symbols]
# Alpine = "ïŒ€ "
# Arch = "ïŒƒ "
# CentOS = "ïŒ„ "
# Debian = "î½ "
# Fedora = "ïŒŠ "
# Gentoo = "ïŒ "
# Macos = "ï…¹ "
# Manjaro = "ïŒ’ "
# Mint = "ïŒ "
# NixOS = "ïŒ“ "
# openSUSE = "ïŒ” "
# SUSE = "ïŒ” "
# Raspbian = "ïŒ• "
# Ubuntu = "ïŒ› "
# RedHatEnterprise = "ïŒ– "
# Linux = "ï…¼ "
# Windows = "îœ "
# Unknown = " "

# [jobs]
# number_threshold = 1
# symbol = "îª¬"
# # symbol = "ï‚…"
# # symbol = "ï‚…"
# # symbol = "ï€“"
# # symbol = "âœ¦"
# style = "blue"

# [container]
# symbol = "î­Ÿ"
# # symbol = "â¬¢"
# style = "red dimmed"

# [conda]
# # disabled because it takes too much space when
# # combined with the Python module
# disabled = false
# ignore_base = false
# symbol = "ğŸ…’ "
# style = "green"

